version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    networks:
      - lyrichunt_network
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: lyric_hunt
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring_app_container
    networks:
      - lyrichunt_network
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/lyric_hunt?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_PROFILES_ACTIVE: "docker"
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      SPRING_DATASOURCE_PLATFORM: org.hibernate.dialect.MySQL8Dialect

networks:
  lyrichunt_network:
    driver: bridge

volumes:
  mysql_data: